/*
 * boot.c - auto-generated by CHDK code_gen.
 */
#include "lolevel.h"
#include "platform.h"
#include "core.h"
#include "dryos31.h"

#define offsetof(TYPE, MEMBER) ((int) &((TYPE *)0)->MEMBER)

const char * const new_sa = &_end;

// Forward declarations
extern volatile int jogdial_stopped;
void JogDial_task_my(void);

extern void task_CaptSeq();
extern void task_InitFileModules();
extern void task_RotaryEncoder();
extern void task_MovieRecord();
extern void task_ExpDrv();

/*----------------------------------------------------------------------
    spytask
-----------------------------------------------------------------------*/
void spytask(long ua, long ub, long uc, long ud, long ue, long uf)
{
    core_spytask();
}

/*----------------------------------------------------------------------
    CreateTask_spytask
-----------------------------------------------------------------------*/
void CreateTask_spytask()
{
    _CreateTask("SpyTask", 0x19, 0x2000, spytask, 0);
}

///*----------------------------------------------------------------------
// Pointer to stack location where jogdial task records previous and current
// jogdial positions
short *jog_position;

/*----------------------------------------------------------------------
    boot()

    Main entry point for the CHDK code
-----------------------------------------------------------------------*/

void __attribute__((naked,noinline)) boot() {
asm volatile (
        "LDR.W           SP, =0x80010000 \n"
        "BL              sub_FC020064 \n"
        "LDR             R2, =0xC0242010 \n"
        "LDR             R1, [R2] \n"
        "ORR.W           R1, R1, #1 \n"
        "STR             R1, [R2] \n"
        "LDR             R0, =0xFCC2858C \n"
        "LDR             R1, =0x10C1000 \n"
        "LDR             R3, =0x10DF4E0 \n"
    "loc_FC020024: \n"
        "CMP             R1, R3 \n"
        "ITT CC \n"
        "LDRCC.W         R2, [R0],#4 \n"
        "STRCC.W         R2, [R1],#4 \n"
        "BCC             loc_FC020024 \n"
        "LDR             R0, =0x10C1000 \n"
        "LDR             R1, =0x1E4E0 \n"
        "BL              sub_FC12F66E \n"
        "LDR             R0, =0xFCBFD1A8 \n"
        "LDR             R1, =0x8000 \n"
        "LDR             R3, =0x333E4 \n"
    "loc_FC020040: \n"
        "CMP             R1, R3 \n"
        "ITT CC \n"
        "LDRCC.W         R2, [R0],#4 \n"
        "STRCC.W         R2, [R1],#4 \n"
        "BCC             loc_FC020040 \n"
        "LDR             R3, =0x333E4 \n"
        "LDR             R1, =0x30BA30 \n"
        "MOV.W           R2, #0 \n"
    "loc_FC020056: \n"
        "CMP             R3, R1 \n"
        "IT CC \n"
        "STRCC.W         R2, [R3],#4 \n"
        "BCC             loc_FC020056 \n"
        "B.W             sub_FC0632CC \n"
);
}

